repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 9.0.0b2
    hooks:
      - id: isort
        name: isort (profile black)
        args: ["--profile", "black"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.1
    hooks:
      - id: mypy
        args: ["src"]
        pass_filenames: false
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        additional_dependencies: ["black[jupyter]"]
